name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda_function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: npm install
        run: npm ci
      - name: deploy
        run: |
        # build /w ncc
